### ISSUE TITLE
allow entering LSS codes on flight page

### ISSUE THREAD

**Issue by steven-omaha** [martinco/LazyMDC#15]
In the flight page, behind LSR and before squawk, add another column to allow for setting the laser spot search code. On the kneeboard, print it in the same place.

Figuring out which flight member uses which LSS code is sumarized in this table:
![Screenshot 2020-11-13 232725](https://user-images.githubusercontent.com/35634100/99127158-e85d7e80-2607-11eb-9078-72037a77e118.png)

Please let me know if these information are not precise enough or unclear.

**Comment by martinco** [comment]
Oh this fell off at some point! Thanks - will get it added
