### ISSUE TITLE
APKWS ordnance string too long for text field

### ISSUE THREAD

**Issue by steven-omaha** [martinco/LazyMDC#19]
See image. I had selected the M-282L.

![Screenshot 2020-11-18 130624](https://user-images.githubusercontent.com/35634100/99528706-fb24da00-299e-11eb-94c9-643d2c5bf5c6.png)

**Comment by steven-omaha** [comment]
Some 2.75 inch rockets and missiles have overly long strings. I would recommend to shorten them. For what is seen in station 2, something like `LAU-131, 7 x M-282L` may work.

**Comment by martinco** [comment]
![image](https://user-images.githubusercontent.com/250888/100350940-9a228500-2fe2-11eb-84d3-32ceb66c2089.png)
