### ISSUE TITLE
AWACS check-in misses callsign

### ISSUE THREAD

**Issue by steven-omaha** [martinco/LazyMDC#20]
See image. Added the callsign as a note. Would be great if this was part of the agency's name.

![Screenshot 2020-11-18 130932](https://user-images.githubusercontent.com/35634100/99528942-4dfe9180-299f-11eb-9680-f0b84d008285.png)

**Comment by martinco** [comment]
It poses an all too common / painful problem:

AWACS Check-In is probably the most useful descriptive info, yet of course the callsign is most useful for crew; It's not actually written anywhere that it's darkstar

Externals participating wont know it's darkstar and will likely look for awacs as that's the only provision in the 2 page freq. overview https://132nd-vwing.github.io/ATRM_Brief/Files/ATRM%20freqs%20overview.pdf 

I see several options and unsure over what I feel is best:

  - Default the notes section on autocomplete to populate with DARKSTAR
  - add DARKSTAR to the agency info and expand AGENCY reducing the notes section further
  - add DARKSTAR to the agency info and enable word wrapping which will always be two lines on nearly every MDC (ugly imo)

**Comment by steven-omaha** [comment]
Intuitively I would have suggested point 2. But what about point 3; when line wrap is enabled, and the string width is shorter than the text box, there should be no second line?

**Comment by martinco** [comment]
It would be both I think expand agency and enable wrap to cover both - will do that as notes tend to be few words

Always easy enough to change if folks complain
