### ISSUE TITLE
Threatsite_?? waypoints not in database / not auto-completed

### ISSUE THREAD

**Issue by steven-omaha** [martinco/LazyMDC#36]
https://mdc.132virtualwing.org/a84ZIZ7G#waypoints

I wanted to add some of `Threatsite_[1-9][0-9]?` navpoints to the flightplan. Those threatsites exist in Range 2, and have an navpoint associated with them in the latest ATRM. Entering Threat, threat, ts or TS as waypoint name does not trigger autocompletion.

**Comment by martinco** [comment]
Closing as the Admin API is now live and more complete / updated mission data is active
