### ISSUE TITLE
Threat database misses AAA

### ISSUE THREAD

**Issue by steven-omaha** [martinco/LazyMDC#38]
We often face ZSU-23-2 and ZSU-23-4. Would be great if they could be added to the list of known threats.

**Comment by martinco** [comment]
check the #instructor-pilots there is a pinned message with credentials to add threats

Added the AAA section which includes the above (assume 57-2) of https://wiki.hoggitworld.com/view/Threat_Database and might go through more tomorrow

**Comment by steven-omaha** [comment]
Thanks for adding the data! Corrected the ZU-23-3 to ZU-23-2 (AFAIK there is no -3).
