### ISSUE TITLE
chg request CV73 TACAN changee to 13X

### ISSUE THREAD

**Issue by 132nd-Entropy** [martinco/LazyMDC#58]
Hi @martinco Im not sure where the master data file is, else I'd edit it myself, can you point me towards it, or change the CV73 tacan to from 73X to 13X ? 

cheers

**Comment by martinco** [comment]
It's handled in the admin page https://mdc.132virtualwing.org/admin I made it so at some point sorry whilst I got the ping I only just noticed it sorry!
