### ISSUE TITLE
Add capacity for a link to the download page without edit access to the kneeboard

### ISSUE THREAD

**Issue by 132Ashilta** [martinco/LazyMDC#7]

**Comment by martinco** [comment]
This is available if you click LNK you get links to download for direct PNG / PDF links

**Comment by martinco** [comment]
Additionally as of 2320f06c0ea46bb05840d0a7aaac7737dc5ba44f if you click LNK download you're provided with snapshot link - so should you edit the page after submitting the link it won't change the download
