### ISSUE TITLE
24-hour time formats

### ISSUE THREAD

**Issue by jkhoel** [martinco/LazyMDC#8]
I notice that at least for me I get 12-hour time formats. Would like to see that forced to 24-hr formats (or selectable)

**Comment by martinco** [comment]
The fields are just type="time" which comes down to your browser / OS locale configuration

24 hour:

![image](https://user-images.githubusercontent.com/250888/95963762-fe590300-0dff-11eb-960e-8b3cb1935005.png)

12 hour:

![image](https://user-images.githubusercontent.com/250888/95963785-03b64d80-0e00-11eb-9944-4f900f3a76b6.png)

These are changed in Control Panel -> Date and Time -> Region -> Change data formats

**Comment by martinco** [comment]
On chrome, this is also influenced by chrome://settings/languages

However it's worth noting that regardless of the display format, the output will always be 24h
